# Compliance server config.toml example

external_port = 8001
internal_port = 8002
needs_auth = false
network_passphrase = "Test SDF Network ; September 2015"

[database]
type = "mysql"
url = "root:@/compliance"

[keys]
# GC7DVHGMSQYAPYXQU652VVHEMZ2OZN4VH44T67QILDHDMBOACMZHQWLW
signing_seed = "SBEL63EBNQUTQ2ZTGHGLLXEMP6THALGS3VQ2N4RVHUWIBB5KGDJWVF3R"
encryption_key = ""

[callbacks]
sanctions = "http://sanctions"
ask_user = "http://ask_user"
fetch_info = "http://fetch_info"

[tls]
certificate_file = "server.crt"
private_key_file = "server.key"
